# Generated by Django 4.1.3 on 2023-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.TextField(default='questions'),
        ),
    ]
