# Generated by Django 4.1.3 on 2023-06-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0006_remove_notification_data_notification_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.TextField(),
        ),
    ]
