# Generated by Django 4.1.3 on 2023-06-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0007_alter_notification_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conta_ml',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meli.contaml'),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('items', 'Items'), ('questions', 'Questions'), ('payments', 'Payments'), ('messages', 'Messages'), ('orders_v2', 'Orders V2'), ('shipments', 'Shipments'), ('orders feedback', 'Orders Feedback'), ('quotations', 'Quotations'), ('invoices', 'Invoices'), ('claims', 'Claims'), ('item competition', 'Item Competition'), ('leads credits', 'Leads Credits'), ('stock fulfillment', 'Stock Fulfillment'), ('best price eligible', 'Best Price Eligible'), ('public candidates', 'Public Candidates'), ('items prices', 'Items Prices'), ('public offers', 'Public Offers'), ('flex handshakes', 'Flex Handshakes')], max_length=50),
        ),
    ]
