# Generated by Django 4.1.3 on 2023-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0008_notification_conta_ml_notification_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaml',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contaml',
            name='link_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contaml',
            name='nivel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contaml',
            name='permalink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
